name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download aws_signing_helper
        run: |
          wget https://rolesanywhere.amazonaws.com/releases/1.1.1/X86_64/Linux/aws_signing_helper -O aws_signing_helper
          chmod +x aws_signing_helper

      - name: Use Certificate Secret
        run: |
          echo "${{ secrets.AWS_CERTIFICATE }}" > certificate.pem

      - name: Use Private Key Secret
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem

      - name: Use AWS Signing Helper
        run: |
          ./aws_signing_helper credential-process \
            --certificate certificate.pem \
            --private-key private_key.pem \
            --trust-anchor-arn arn:aws:rolesanywhere:eu-west-1:339712756401:trust-anchor/b8c4373f-5a19-40db-8d53-7e7d8e95b866 \
            --profile-arn arn:aws:rolesanywhere:eu-west-1:339712756401:profile/5235e66e-78d3-4d9e-b8e1-0343b150f876 \
            --role-arn arn:aws:iam::339712756401:role/roles-anywhere
